Fix battery sim
Shenzhen-Robotics-Alliance/maple-sim pull request #66
Opened 2024-12-15 01:32 UTC by Daniel1464

Currently, MapleSim's battery sim can return NaN in fringe scenarios, causing RobotController.getBatteryVoltage() to return invalid values. This can be detrimental if PathPlanner's SwerveSetpointGenerator is used(or other calls to RobotController.getBatteryVoltage are used in the code), as they rely on RobotController.getBatteryVoltage.

This commit gives two safeguard:
1. It halves the current of the battery sim
2. It handles NaN scenarios by printing an error msg and defaulting to the robot controller's brownout voltage instead

Currently, i dont exactly know what causes this.

2024-12-15 01:44 UTC, Daniel1464 commented
Note: defaulting to the brownout voltage gives like 6.75 volts to it, which ends up slowing down pathplanner's setpoint gen a lot, so i decided to do 12 volts instead

2024-12-16 01:34 UTC, mmilunicmobile requested changes
We shouldn't still be dividing the total current by 2.

2024-12-16 01:34 UTC, mmilunicmobile commented on project/src/main/java/org/ironmaple/simulation/motorsims/SimulatedBattery.java
>                  / 2.0;
Shouldn't this not be divided by 2? I believe that was a temporary fix for current drawing too much, but we figured out the underlying cause of that.

2024-12-16 06:17 UTC, catr1xLiu commented on project/src/main/java/org/ironmaple/simulation/motorsims/SimulatedBattery.java
>                  / 2.0;
I guess you're right.  I was also wondering why it was there.

2024-12-19 06:16 UTC, merged

2024-12-19 06:20 UTC, catr1xLiu commented
I added the Javadocs and I think this is ready for merging.

@Daniel1464 @mmilunicmobile Thank you so much for working on this, the battery simulation is working great now!